### ISSUE TITLE
Demo Not working

### ISSUE THREAD

**Issue by sagialter88** [leifermendez/swipe-angular-list#2]
Hi,

I'm getting the above error trying to run your demo code:

![image](https://user-images.githubusercontent.com/67538036/85945065-e12d2100-b943-11ea-8195-8ed6f946cf39.png)

my package.json file content:

{
  "name": "swipe-list",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "rxjs": "~6.5.5",
    "swipe-angular-list": "^1.0.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}

**Comment by leifermendez** [comment]
Hi @sagialter88 in a moment check :)

**Comment by leifermendez** [comment]
Okay, if you're right, I missed not declaring one works, but I figured it out.I also updated the Angle 10 demo and it works fine. Can you check and comment Thank

**Comment by leifermendez** [comment]
https://stackblitz.com/edit/angular-ejzvpz
