### ISSUE TITLE
Children undefined

### ISSUE THREAD

**Issue by riwos** [leifermendez/swipe-angular-list#3]
Hi,

I think that assumption is wrong about structure
```
<ng-template  #customTemplateSrc  let-item='item'  let-id='id'>
   <div  style="display: flex;">
      <div  style="padding-right: 10px;">
         <img  style="width:60px;height:60px;border-radius:60px;"
            [src]="'https://api.adorable.io/avatars/400/'+id+'.png'"  alt="">
      </div>
       ...
   </div>
</ng-template>
```

I have a similiar structure but without one level i.e. You have 3 levels and I have only 2..

```
<ng-template #customTemplateSrc let-item="item">
   <div style="display: flex;">
      <div class="col-md-2">
         {{ item.c }}
      </div>
      <div class="col-md-2">
         {{ item.s }}
      </div>
      <div class="col-md-7">
         {{ item.n }}
      </div>
      <div class="col-md-2">
         {{ item.p }}
      </div>
      <div class="col-md-1">
         {{ item.q }}
      </div>
   </div>
</ng-template>
```
In my case I've got that error in the browser like this one:
<img width="449" alt="Screenshot 2020-07-11 at 07 32 18" src="https://user-images.githubusercontent.com/684729/87218231-bc27ad80-c348-11ea-95f6-033fb709acc5.png">

What I found so far the issue is here, because you don't check if collection is 'undefined':
(ngAfterViewInit method, line 209)
<img width="540" alt="Screenshot 2020-07-11 at 12 40 42" src="https://user-images.githubusercontent.com/684729/87223334-f35f8400-c373-11ea-94c4-69dd848d0f56.png">

If you can add one more extra condition or give me advice what i'm doing wrong I will appreciate it

**Comment by leifermendez** [comment]
Hi. Yes I know about this error, the next week will am solve bug, but if you a need fix your bug. A simple solution is wrapped all your '<div style ...' inside other div '<div><div style ... ></div>

**Comment by riwos** [comment]
Hi @leifermendez,

Have you have a chance to apply a fix ?? 

Unfortunately your proposal doesn't work and I get the same error all the time.. 

Also I think and you can consider that to 'emit' callback when you swipe an element and pass in x-coordinates. I mean it would be nice to know when I swipe but no click the element. The click and swipe should be independents actions. Now when you swipe incorrectly the click event is raised as well.

Good stuff anyway !!

**Comment by leifermendez** [comment]
Hi, tomorrow I start to check. Can you nominate https://stars.github.com/nominate 🌟

**Comment by leifermendez** [comment]
You must check version number, remember install `npm i swipe-angular-list@latest --save` (1.0.6) today.
In this version add new callback function (swipe), you can check [live demo ](https://stackblitz.com/edit/angular-ejzvpz)

Can you collaborate update the readme file with new updates and instructions?

![image](https://user-images.githubusercontent.com/15802366/87656878-5aa57b80-c75a-11ea-8955-c75835a3a19a.png)

**Comment by riwos** [comment]
@leifermendez thanks ! it works ;)
