### ISSUE TITLE
Scroll doesn't work on mobile devices

### ISSUE THREAD

**Issue by riwos** [leifermendez/swipe-angular-list#5]
Hi,

The scroll doesn't work on mobile devices. I've checked on iphone and android as well. 
It is easy replicate on your demo page: [LIVE DEMO](https://angular-ejzvpz.stackblitz.io/) 

Hava a look on screenshot
<img width="522" alt="Screenshot 2020-07-18 at 16 55 41" src="https://user-images.githubusercontent.com/684729/87856668-6b9beb80-c918-11ea-9c75-6ae047ab5644.png">

**Comment by leifermendez** [comment]
![image](https://user-images.githubusercontent.com/15802366/87857177-f256c580-c924-11ea-99bb-535e309394c0.png)

You need add the next css class 
```css
* {
  touch-action: pan-y !important;
}

```
