### ISSUE TITLE
editTemplate showing

### ISSUE THREAD

**Issue by NerdZeus** [leifermendez/swipe-angular-list#6]
Even when we do not include editTemplate, it shows with a fallback label "edit". I am trying to have one icon, i.e. trash icon but I get the edit template as well

**Comment by leifermendez** [comment]
Hi! You can set with`null` ` [editTemplate]="null"` , same way for `[trashTemplate]="null" `

![image](https://user-images.githubusercontent.com/15802366/101144013-03744a80-3618-11eb-9559-2f0ba8cae79c.png)


![image](https://user-images.githubusercontent.com/15802366/101143953-ed668a00-3617-11eb-9d04-31863a7de6ae.png)

**Comment by leifermendez** [comment]
Can you help add more readme. More explicity
